apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  template:
    metadata:
      labels: { app: api }
    spec:
      imagePullSecrets:
{{- if .Values.image.pullSecrets }}
{{ toYaml .Values.image.pullSecrets | indent 8 }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports: 
          - containerPort: 3001
        envFrom:
        - configMapRef: { name: api-config }
        - secretRef: { name: api-secret }
        readinessProbe:
          httpGet: { path: /health, port: 3001 }
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 3001 }
          initialDelaySeconds: 20
          periodSeconds: 20
        resources: {{- toYaml .Values.resources | nindent 10 }}
